FROM mongo-express

ENV ME_CONFIG_MONGODB_ADMINUSERNAME="rawand"
ENV ME_CONFIG_MONGODB_ADMINPASSWORD="rawand"
ENV ME_CONFIG_MONGODB_SERVER="mongo-db"

#cmnd sudo docker build -t mongo-express .
#cmnd sudo docker run -d -p 8081:8081 --net mongo --name mongo-express  mongo-express