FROM mongo 

ENV MONGO_INITDB_ROOT_USERNAME="rawand"
ENV MONGO_INITDB_ROOT_PASSWORD="rawand"

 
# cmd build :sudo docker build -t mongo .
# cmd run   : sudo docker run -d --name mongo-db  --net mongo -p 27017:27017 mongo 
#docker it :
#$> use admin
#$> db.auth("admin", passwordPrompt())
