version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rawand
      - MONGO_INITDB_ROOT_PASSWORD=rawand 
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rawand
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rawand
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always
#cmnd: sudo docker-compose -f mongo.yaml up
